# Generated by Django 5.2 on 2025-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=30)),
                ('release', models.DateField()),
                ('director', models.CharField(max_length=30)),
                ('license_type', models.CharField(max_length=30)),
                ('license_url', models.URLField()),
                ('source_url', models.URLField()),
                ('cover', models.ImageField(upload_to='covers/')),
                ('movie_url', models.FileField(upload_to='movies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
