# Generated by Django 5.2 on 2025-05-03 09:53

import movie_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_cover_alter_movie_movie_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=30)),
                ('release', models.DateField()),
                ('director', models.CharField(max_length=30)),
                ('license_type', models.CharField(max_length=30)),
                ('license_url', models.URLField()),
                ('source_url', models.URLField()),
                ('cover', models.ImageField(upload_to=movie_app.models.cover_upload_path)),
                ('movie_url', models.FileField(upload_to=movie_app.models.movie_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
