# Generated by Django 5.2 on 2025-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='cover',
            field=models.ImageField(upload_to='trailer'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='movie_url',
            field=models.FileField(upload_to='trailer'),
        ),
    ]
